nu: better path and install-nushell

diff --git a/.local/bin/install-nushell b/.local/bin/install-nushell
--- a/.local/bin/install-nushell
+++ b/.local/bin/install-nushell
@@ -4,14 +4,6 @@
 # Its responsibility is to query the system to determine what OS the system
 # has, fetch and install the appropriate build of nushell
 
-get_latest_release() {
-	curl --silent https://api.github.com/repos/nushell/nushell/releases/latest | awk -F\" '/tag_name/{print $(NF-1)}'
-}
-
-release_url() {
-	echo "https://github.com/nushell/nushell/releases"
-}
-
 download_release_from_repo() {
 	local version="$1"
 	local os_info="$2"
@@ -19,7 +11,7 @@ download_release_from_repo() {
 
 	local filename="nu-$version-$os_info.tar.gz"
 	local download_file="$tmpdir/$filename"
-	local archive_url="$(release_url)/download/$version/$filename"
+	local archive_url="https://github.com/nushell/nushell/releases/download/$version/$filename"
 
 	info "Url" "$archive_url"
 
@@ -36,20 +28,8 @@ error() {
 	command printf '\033[1;31mError\033[0m: %s\n\n' "$1" 1>&2
 }
 
-warning() {
-	command printf '\033[1;33mWarning\033[0m: %s\n\n' "$1" 1>&2
-}
-
-request() {
-	command printf '\033[1m%s\033[0m\n' "$1" 1>&2
-}
-
 eprintf() {
 	command printf '%s\n' "$1" 1>&2
-}
-
-bold() {
-	command printf '\033[1m%s\033[0m' "$1"
 }
 
 # Check if it is OK to upgrade to the new version
@@ -57,7 +37,7 @@ upgrade_is_ok() {
 	local will_install_version="$1"
 	local install_dir="$2"
 
-	local nu_bin="$install_dir/nu/nu"
+	local nu_bin="$install_dir/nu"
 
 	if [[ -n "$install_dir" && -x "$nu_bin" ]]; then
 		local prev_version="$( ($nu_bin --version 2>/dev/null || echo 0.1) | sed -E 's/^.*([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')"
@@ -116,21 +96,6 @@ parse_os_pretty() {
 	esac
 }
 
-# return true(0) if the element is contained in the input arguments
-# called like:
-#  if element_in "foo" "${array[@]}"; then ...
-element_in() {
-	local match="$1"
-	shift
-
-	local element
-	# loop over the input arguments and return when a match is found
-	for element in "$@"; do
-		[ "$element" == "$match" ] && return 0
-	done
-	return 1
-}
-
 create_tree() {
 	local install_dir="$1"
 
@@ -142,21 +107,6 @@ create_tree() {
 	if [ "$?" != 0 ]; then
 		error "Could not create directory layout. Please make sure the target directory is writeable: $install_dir"
 		exit 1
-	fi
-}
-
-install_version() {
-	local install_dir="$1"
-
-	local latest_version="$(get_latest_release)"
-	info 'Installing' "latest version of nu ($latest_version)"
-	install_release "$latest_version" "$install_dir"
-
-	if [ "$?" == 0 ]; then
-		info 'Finished' "installation. nu available at $install_dir/nu/nu."
-		local nu_bin="$install_dir/nu/nu"
-		local version="$($nu_bin --version)"
-		info "Test" "version: $version"
 	fi
 }
 
@@ -172,11 +122,15 @@ install_release() {
 		)"
 		exit_status="$?"
 		if [ "$exit_status" != 0 ]; then
-			error "Could not download nushell version '$version'. See $(release_url) for a list of available releases"
+			error "Could not download nushell version '$version'."
 			return "$exit_status"
 		fi
 
-		install_from_file "$download_archive" "$install_dir"
+		local extract_dir="$(mktemp -d)"
+
+		extract_to_dir "$download_archive" "$extract_dir"
+
+		install_to_target "$extract_dir" "$install_dir"
 	else
 		# existing install, or upgrade problem
 		return 1
@@ -201,28 +155,38 @@ download_release() {
 	download_release_from_repo "$version" "$os_info" "$download_dir"
 }
 
-install_from_file() {
+# extracts the given archive file to a directory
+# it also renames the named binary to just `nu`
+extract_to_dir() {
 	local archive="$1"
-	local install_dir="$2"
+	local target_dir="$2"
 
 	local dir_name="$(basename "$archive" .tar.gz)"
 
-	create_tree "$install_dir"
-
 	info 'Extracting' "nushell binary"
 	# extract the files to the specified directory
-	tar -xf "$archive" -C "$install_dir"
+	tar -xf "$archive" -C "$target_dir"
+
+	# rename the full name to something shorter
+	mv "$target_dir/$dir_name" "$target_dir/nu"
+}
+
+# move just the main nu binary to target
+# there are some plugins shipped and we don't want these
+install_to_target() {
+	local extracted_dir="$1"
+	local install_dir="$2"
 
 	local nu_bin="$install_dir/nu/nu"
 
-	# remove old
+	create_tree "$install_dir"
+
 	if [[ -x "$nu_bin" ]]; then
-		info 'Deleting' "$install_dir/nu"
-		rm -rf "$install_dir/nu"
+		info 'Deleting old' "$nu_bin"
+		rm "$nu_bin"
 	fi
 
-	# rename the full name to something shorter
-	mv "$install_dir/$dir_name" "$install_dir/nu"
+	mv "$extracted_dir/nu/nu" "$install_dir/nu"
 }
 
 check_architecture() {
@@ -243,11 +207,21 @@ check_architecture() {
 	return 1
 }
 
-# return if sourced (for testing the functions above)
-return 0 2>/dev/null
+main() {
+	local install_dir="$1"
 
-install_dir="$HOME"
+	check_architecture "$(uname -m)" || exit 1
 
-check_architecture "$(uname -m)" || exit 1
+	local latest_version="$(curl --silent https://api.github.com/repos/nushell/nushell/releases/latest | awk -F\" '/tag_name/{print $(NF-1)}')"
+	info 'Installing' "latest version of nu ($latest_version)"
+	install_release "$latest_version" "$install_dir"
 
-install_version "$install_dir"
+	if [ "$?" == 0 ]; then
+		info 'Finished' "installation. nu available at $install_dir/nu."
+		local nu_bin="$install_dir/nu"
+		local version="$($nu_bin --version)"
+		info "Test" "version: $version"
+	fi
+}
+
+main "$HOME/.local/bin"
